# source: https://www.vantage-ai.com/blog/speed-up-your-python-development-workflow-with-pre-commit-and-makefile
# Note: exclude uses python regex
exclude: '^.*\.(md|html|css|js|txt)$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-ast
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
